// Copyright 2025 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// validatorgen generates validator functions for different
// schema argument types.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"

	"github.com/altshiftab/utils_go/pkg/json/schema/internal/argtype"
	schema "github.com/altshiftab/utils_go/pkg/json/schema/types"
)

type keyword struct {
	name        string
	argType     schema.ArgType
	alwaysValid bool
}

const header = `// Copyright 2025 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by validatorgen; DO NOT EDIT.

package validator

import (
	"fmt"

	schema "github.com/altshiftab/utils_go/pkg/json/schema/types"
)
`

func main() {
	printValidatorConvertors()
}

// validatorFn is the template for a validator function.
// %[1] is the schema argument type.
// %[2] is the function name.
const validatorFn = `// %[2]s converts a validator function that accepts
// [types.ArgType%[1]s] to one that can be stored in a [types.Keyword].
func %[2]s(fn func(arg schema.Part%[1]s, instance any, state *schema.ValidationState) error) func(schema.PartValue, any, *schema.ValidationState) error {
	return func(arg schema.PartValue, instance any, state *schema.ValidationState) error {
		v, err := To%[1]s(arg)
		if err != nil {
			return err
		}
		return fn(v, instance, state)
	}
}`

// convertorFn is the template for a convertor function.
// %[1] is the schema argument type.
// %[2] is a description for an error message.
const convertorFn = `// To%[1]s converts arg into a [types.Part%[1]s].
func To%[1]s(arg schema.PartValue) (schema.Part%[1]s, error) {
	v, ok := arg.(schema.Part%[1]s)
	if !ok {
		var zero schema.Part%[1]s
		return zero, fmt.Errorf("got %%T, expect %[2]s", arg)
	}
	return v, nil
}`

// printValidatorConvertors writes out the validation conversion functions.
// These are functions that take a value of type any,
// verify that the value is of the right type,
// and then invoke the real validation function.
// This lets us write the validation functions with the correct type,
// without having to worry about always type checking.
func printValidatorConvertors() {
	buf := new(bytes.Buffer)

	fmt.Fprint(buf, header)
	fmt.Fprintln(buf)

	for t := schema.ArgTypeBool; t <= schema.ArgTypeAny; t++ {
		tn := argtype.Name(t)
		name := "ArgType" + tn
		fmt.Fprintln(buf)
		fmt.Fprintf(buf, validatorFn, tn, name)

		// For numbers we need to accept multiple possibilities,
		// so those convertors are written by hand.
		if t == schema.ArgTypeInt || t == schema.ArgTypeFloat {
			continue
		}

		var desc string
		//nolint:exhaustive // Int and Float are skipped by the continue above.
		switch t {
		case schema.ArgTypeBool:
			desc = "bool"
		case schema.ArgTypeString:
			desc = "a string"
		case schema.ArgTypeStrings:
			desc = "an array of strings"
		case schema.ArgTypeStringOrStrings:
			desc = "a string or an array of strings"
		case schema.ArgTypeSchema:
			desc = "a schema"
		case schema.ArgTypeSchemas:
			desc = "an array of schemas"
		case schema.ArgTypeMapSchema:
			desc = "a mapping from strings to schemas"
		case schema.ArgTypeSchemaOrSchemas:
			desc = "a single schema or an array of schemas"
		case schema.ArgTypeMapArrayOrSchema:
			desc = "a mapping from strings to either a schema or an array of strings"
		case schema.ArgTypeAny:
			desc = "any type"
		default:
			panic("can't happen")
		}

		fmt.Fprintln(buf)
		fmt.Fprintf(buf, convertorFn, tn, desc)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	//nolint:gosec // Generated source files are world-readable by design.
	if err := os.WriteFile("validators.go", formatted, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
