package main

import (
	"bytes"
	"errors"
	"flag"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"testing"

	"github.com/altshiftab/utils_go/pkg/errors/types/empty_error"
)

// runMain invokes run() with a controlled argv, capturing anything written to
// stdout. The global flag set, os.Args and os.Stdout are saved and restored so
// the call can be repeated. These tests must not run in parallel because they
// mutate this process-wide state.
func runMain(t *testing.T, args ...string) (string, error) {
	t.Helper()

	origArgs := os.Args
	origCommandLine := flag.CommandLine
	origStdout := os.Stdout
	defer func() {
		os.Args = origArgs
		flag.CommandLine = origCommandLine
		os.Stdout = origStdout
	}()

	os.Args = append([]string{"translate_json_object"}, args...)
	flag.CommandLine = flag.NewFlagSet(os.Args[0], flag.ContinueOnError)

	readEnd, writeEnd, err := os.Pipe()
	if err != nil {
		t.Fatalf("failed to create stdout pipe: %v", err)
	}
	os.Stdout = writeEnd

	captured := make(chan string, 1)
	go func() {
		var buf bytes.Buffer
		_, _ = io.Copy(&buf, readEnd)
		captured <- buf.String()
	}()

	runErr := run()

	_ = writeEnd.Close()
	stdout := <-captured
	_ = readEnd.Close()

	return stdout, runErr
}

const testInput = `{"greeting": "hello", "enabled": true, "pi": 3.14, "nums": [1, 2]}`

const testExpectedRaw = `// Code generated by "translate_json_object"; DO NOT EDIT.
package testpkg

const (
enabled = true
greeting = "hello"
pi = 3.14
)

var (
nums = []string{"1", "2"}
)`

func expectedOutput(t *testing.T) string {
	t.Helper()

	formatted, err := format.Source([]byte(testExpectedRaw))
	if err != nil {
		t.Fatalf("failed to format expected output: %v", err)
	}

	return string(formatted)
}

func TestRunStdout(t *testing.T) { //nolint:paralleltest // shares process-global state through run()
	inputPath := filepath.Join(t.TempDir(), "input.json")
	if err := os.WriteFile(inputPath, []byte(testInput), 0o600); err != nil {
		t.Fatalf("failed to write input file: %v", err)
	}

	stdout, err := runMain(t, "-path", inputPath, "-package-name", "testpkg")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if expected := expectedOutput(t) + "\n"; stdout != expected {
		t.Fatalf("unexpected output.\nGot:\n%s\nWant:\n%s", stdout, expected)
	}
}

func TestRunGofile(t *testing.T) {
	inputPath := filepath.Join(t.TempDir(), "input.json")
	if err := os.WriteFile(inputPath, []byte(testInput), 0o600); err != nil {
		t.Fatalf("failed to write input file: %v", err)
	}

	t.Chdir(t.TempDir())
	t.Setenv("GOFILE", "config.go")

	stdout, err := runMain(t, "-path", inputPath, "-package-name", "testpkg")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if stdout != "" {
		t.Fatalf("expected no stdout output when GOFILE is set, got: %q", stdout)
	}

	generatedData, err := os.ReadFile("config_generated.go")
	if err != nil {
		t.Fatalf("failed to read generated file: %v", err)
	}

	if expected := expectedOutput(t); string(generatedData) != expected {
		t.Fatalf("unexpected generated file content.\nGot:\n%s\nWant:\n%s", generatedData, expected)
	}
}

func TestRunErrors(t *testing.T) { //nolint:paralleltest // shares process-global state through run()
	testCases := []struct {
		name      string
		args      func(t *testing.T) []string
		wantEmpty bool
	}{
		{
			name:      "empty path",
			args:      func(t *testing.T) []string { return nil },
			wantEmpty: true,
		},
		{
			name: "nonexistent path",
			args: func(t *testing.T) []string {
				return []string{"-path", filepath.Join(t.TempDir(), "missing.json")}
			},
		},
		{
			name: "invalid json",
			args: func(t *testing.T) []string {
				inputPath := filepath.Join(t.TempDir(), "input.json")
				if err := os.WriteFile(inputPath, []byte("{not json"), 0o600); err != nil {
					t.Fatalf("failed to write input file: %v", err)
				}
				return []string{"-path", inputPath}
			},
		},
	}

	for _, testCase := range testCases { //nolint:paralleltest // shares process-global state through run()
		t.Run(testCase.name, func(t *testing.T) {
			_, err := runMain(t, testCase.args(t)...)
			if err == nil {
				t.Fatal("expected an error, got nil")
			}

			if testCase.wantEmpty {
				if _, ok := errors.AsType[*empty_error.Error](err); !ok {
					t.Fatalf("expected an empty_error.Error, got: %v", err)
				}
			}
		})
	}
}
